### PR TITLE
PROJECT: ADVANCED BUILDING BLOCKS (Project 1: Bubble Sort) in Ruby

### PR DESCRIPTION
**Pull request by bolah2009**
# Project 1: Bubble Sort

## PROJECT: ADVANCED BUILDING BLOCKS (Project 1: Bubble Sort)

This is the first project of the main `Ruby` curriculum at [Microverse](https://www.microverse.org/) - @microverseinc

#### The objective are as follows:

1. Build a method `#bubble_sort` that takes an array and returns a sorted array.

``` rb
def bubble_sort(array)
  not_sorted = true, n = array.length - 1
  sorting(not_sorted, array, n)
  array
end

def sorting(not_sorted, array, index)
  while not_sorted
    not_sorted = false
    (0...index).each do |i|
      next unless array[i] > array[i + 1]

      array[i], array[i + 1] = array[i + 1], array[i]
      not_sorted = true
    end
    index -= 1
  end
end

p bubble_sort([4, 3, 78, 2, 0, 2])
#=> [0,2,2,3,4,78]
```

2. Build another method `#bubble_sort_by` which sorts an array by accepting a block

``` rb
def bubble_sort_by(array)
  not_sorted = true, n = array.length - 1
  while not_sorted
    not_sorted = false
    (0...n).each do |i|
      next unless yield(array[i], array[i + 1]) > 0

      array[i], array[i + 1] = array[i + 1], array[i], not_sorted = true
    end
    n -= 1
  end
  p array
end

bubble_sort_by(['hi', 'hello', 'hey']) do |left, right|
  left.length <=> right.length
end
# ["hi", "hey", "hello"]
```

#### Contact
* [Web](https://bolabuari.com/) - [Twitter](https://twitter.com/bolah2009) - [GitHub](https://github.com/bolah2009/) - [GitLab](https://gitlab.com/bolah2009/) - [LinkedIn](https://www.linkedin.com/in/bolah2009/)

### CODE REVIEW

**Comment by dipto0321** [comment]
# Awesome job 👏 🏆 🚀 

Hi @bolah2009 ,

This project was nice. Neat and clean. Just a minor thing you have to fix before merging into master. Remove `p` from [here](https://github.com/bolah2009/bubble-sort/blob/0ed534429662ae660c906147e017cea083779c6c/bubble_sort_by.rb#L13). After that you can merge it. This is from me 👍 

Thanks 😃

**Comment by bolah2009** [comment]
> # Awesome job   
> Hi @bolah2009 ,
> 
> This project was nice. Neat and clean. Just a minor thing you have to fix before merging into master. Remove `p` from [here](https://github.com/bolah2009/bubble-sort/blob/0ed534429662ae660c906147e017cea083779c6c/bubble_sort_by.rb#L13). After that you can merge it. This is from me 
> 
> Thanks

Hey @dipto0321 , thanks for the review! ✔️
Can you explain why I shouldn't use the `p` ? I did because it prints out the output so I can confirm it solves the test case. Suggestion of how else it could have been done will be appreciated. Thanks again 👍🏾

**Comment by dipto0321** [comment]
Hi @bolah2009 ,

Thanks, man. For asking! If you check `buuble_sort` method what you did, you simply return the sorted array. And then you use p before calling the function. You can do the same thing with `bubble_sort_by`. It will be better if you return the result. Suppose you wanna use `bubble_sort_by` method's result for some reason. But if you use `p` inside that you can't use the value. Because it doesn't return you anything. 🙂 
But if you simply return the value like your `bubble_sort` you can use it. For printing the value you can simply do this 
```
p bubble_sort_by(['hi', 'hello', 'hey']) do |left, right|
  left.length <=> right.length
end
```
Same like `p bubble_sort([4, 3, 78, 2, 0, 2])`

Thanks 🙂

**Comment by bolah2009** [comment]
> Hi @bolah2009 ,
> 
> Thanks, man. For asking! If you check `buuble_sort` method what you did, you simply return the sorted array. And then you use p before calling the function. You can do the same thing with `bubble_sort_by`. It will be better if you return the result. Suppose you wanna use `bubble_sort_by` method's result for some reason. But if you use `p` inside that you can't use the value. Because it doesn't return you anything. 
> But if you simply return the value like your `bubble_sort` you can use it. For printing the value you can simply do this
> 
> ```
> p bubble_sort_by(['hi', 'hello', 'hey']) do |left, right|
>   left.length <=> right.length
> end
> ```
> Same like `p bubble_sort([4, 3, 78, 2, 0, 2])`
> 
> Thanks

Thanks for the response, @dipto0321 !!! :+1: 
However, this didn't work as I have tried it before resorting to this. 
When written in this format:

```rb
p bubble_sort_by(['hi', 'hello', 'hey']) do |left, right|
  left.length <=> right.length
end
```
It returns the following error:

```bash
$ ruby bubble_sort_by.rbTraceback (most recent call last):
        3: from bubble_sort_by.rb:16:in `<main>'
        2: from bubble_sort_by.rb:6:in `bubble_sort_by'
        1: from bubble_sort_by.rb:6:in `each'
bubble_sort_by.rb:7:in `block in bubble_sort_by': no block given (yield) (LocalJumpError)
```
Note that this method can't be compared to the `bubble_sort` method since this is also passing a block.

Also, you didn't answer my question `Can you explain why I shouldn't use the `*p*` ?`
Thanks again @dipto0321 :+1:

**Comment by dipto0321** [comment]
Hi @bolah2009 ,

You can try this `p bubble_sort_by(['hi', 'hello', 'hey']) { |left, right| left.length <=> right.length }`  You may ask me why I didn't use `do...end` [here ](https://stackoverflow.com/questions/5587264/do-end-vs-curly-braces-for-blocks-in-ruby) is the answer.

or

```
arr = ['hi', 'hello', 'hey']
bubble_sort_by(arr) do |left, right|
  left.length <=> right.length
end
p arr
```
> Can you explain why I shouldn't use the `p` ?

Every sorting method return a new array or just sort the passing array. If you check ruby's, python's or any language built-in sort libraries you can see it returns a new sorted array or just sorted the passing array without returning anything. In ruby's built-in sorting method there are two `sort` (return a new array without affecting the original one) and `sort!` (return a new array with affecting the original). Also, you can ask other ruby community about this 🙂 

> Note that this method can't be compared to the `bubble_sort` method since this is also passing a block.

I want to say that in your `bubble_sort` it returned the `array` after sorting rather than printing it. The same thing also should be done with `bubble_sort_by`. That's it. I knew the difference between the two methods.


Thanks 👍

**Comment by bolah2009** [comment]
Thanks @dipto0321 ,

> You are questioning me until you get the absolute idea on a topic. I really like this strategy.

Also, thanks for your patience and understanding. 
This is my first Microverse project in ruby, and I wanted to get more context on why I should remove the `p` since it's not an error and not against the project rubric. 
Now, I fully understand why you made the judgement and thanks for that. I will change the position of the `p`.
PS: Do I need to submit another review or you approve?

**Comment by dipto0321** [comment]
Hi @bolah2009 ,

> PS: Do I need to submit another review or you approve?

No need to send another request man 🙂 . I already give you a 👍 . So you can merge it and move ahead ☺️ Best of luck for your next project.

Thanks 🙏

**Pull request merged**
